[id="network-install-overview_{context}"]
= Network install overview

A network installation allows you to install {productname} to a system that has access to an installation server. At a minimum, two systems are required for a network installation:

*PXE Server:* A system running a DHCP server, a TFTP server, and an HTTP, HTTPS, FTP, or NFS server. While each server can run on a different physical system, the procedures in this section assume a single system is running all servers.

*Client:* The system to which you are installing {productname}. Once installation starts, the client queries the DHCP server, receives the boot files from the TFTP server, and downloads the installation image from the HTTP, HTTPS, FTP or NFS server. Unlike other installation methods, the client does not require any physical boot media for the installation to start.

[NOTE]
====
To boot a client from the network, configure it in BIOS/UEFI or a quick boot menu. On some hardware, the option to boot from a network might be disabled, or not available.
====

The workflow steps to prepare to install {productname} from a network using PXE are as follows:

.Steps

. Export the installation ISO image (or the installation tree) to an NFS, HTTPS, HTTP, or FTP server.
. Configure the TFTP server and DHCP server, and start the TFTP service on the PXE server.
. Boot the client, and start the installation.


[IMPORTANT]
====
The GRUB2 boot loader supports a network boot from HTTP in addition to a TFTP server. Sending the boot files (the kernel and initial RAM disk - vmlinuz and initrd) over this protocol might be slow and result in timeout failures. An HTTP server does not carry this risk, but it is recommended that you use a TFTP server when sending the boot files.
====

