include::ROOT:partial$attributes.adoc[]
include::partial$local-attributes.adoc[]
[id="installation-methods_{context}"]
= Installation methods

You can install {productname} using one of the following methods:

Quick install::
Install {productname} on AMD64, Intel 64, and 64-bit ARM architectures using the graphical user interface. The quick installation assumes that you are familiar with {productname} and your environment, and that you can accept the default settings provided by the installation program.

Graphical install::
Install {productname} using the graphical user interface and customize the graphical settings for your specific requirements.

Automated install::
Install {productname} using Kickstart. The automated installation allows you to perform unattended operating system installation tasks.

[discrete]
== Additional resources

* To perform a graphical installation on AMD64, Intel 64, and 64-bit ARM architectures using the graphical user interface, see xref:standard-install:con_installation-workflow.adoc[Installation workflow].
* To perform an automated install using Kickstart, see the xref:advanced-install:index.adoc[_Performing an advanced installation_] document.
